AWSTemplateFormatVersion: 2010-09-09
Description: Hyperglance Actions Deployment Template

Parameters:
  BucketName:
    Description: OPTIONAL - Name of Bucket where Action Payloads will be delivered, defaults to hyperglance-actions
    Type: String
    Default: 'hyperglance-actions'
  DryMode:
    Description: OPTIONAL - Deploy functions with Dry Mode Enabled, defaults to True.
    Type: String
    Default: 'true'
    AllowedValues: [true, false, yes, y, no, n]
  SnapShotBeforeTerminate:
    Description: OPTIONAL - Snapshot an Instance before terminating, defaults to true for safety
    Type: String
    Default: 'true'
    AllowedValues: [true, false, yes, y, no, n]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: BucketOwnerFullControl
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        - ExpirationInDays: 3
      Tags:
        - Key: Deployed-By
          Value: hyperglance-actions
        - key: Description
          Value: Bucket for Action Payload Delivery
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Hyperglance Actions
      TopicName: hyperglance-actions
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
      Statement:
        - Sid: ""
          Effect: "Allow"
          Principal:
            Service:
              - "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
      Policies:
        - 
          PolicyName: "hyperglance_actions_execution_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - 
                  Effect: "Allow"
                  Action:
                    - dynamodb:DeleteTable
                    - ecr-public:BatchDeleteImage
                    - ec2:CreateSnapshot
                    - ec2:DeleteInternetGateway
                    - ec2:DetachInternetGateway
                    - ec2:DeleteKeyPair
                    - ec2:DeleteNatGateway
                    - ec2:DeleteSecurityGroup
                    - ec2:StopInstances
                    - ec2:TerminateInstances
                    - elb:DeleteLoadBalancer
                    - rds:DeleteDBCluster
                    - redshift:DeleteCluster
                    - s3:PutPublicAccessBlock
                    - s3:PutEncryptionConfiguration
                    - s3:PutBucketVersioning
                    - workspaces:StopWorkspaces
                    - workspaces:TerminateWorkspaces
                    - sts:GetCallerIdentity
                    - sts:AssumeRole
                  Resource: "*"
  unction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that parses, routes and performs infrastructure remediations based on configured Hyperglance Rules
      FunctionName: hyperglance-actions
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !Ref Role
      Runtime: python3.8
      Timeout: 120
      Environment:
        Variables:
          DryRun: !Ref DryMode
          BucketName: !Ref BucketName
          SnapShotBeforeTerminate: !Ref SnapShotBeforeTerminate 
      Code:
        ZipFile: hyperglance_actions.zip
      Tags:
        - Key: Deployed-By
          Value: hyperglance-actions
        - key: Description
          Value: Lambda for Action Payload Routing, Processing and Remediation